<?php

use Illuminate\Database\Seeder;

class AccountingTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Math1011',
            'course_title' => 'Mathematics for Social Sciences',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'instructor_name' => 'worku@gmail.com',
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'FLEn1011',
            'course_title' => 'Communicative English Language I',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'instructor_name' => 'worku@gmail.com',
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'LoCT 1011',
            'course_title' => 'Logic & Critical Thinking',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' =>0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Psch1011',
            'course_title' => 'General Psychology',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'ECON 1011',
            'course_title' => 'Economics',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'IRGI 1012',
            'course_title' => 'Global Trend',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'GeES1011',
            'course_title' => 'Geography of Ethiopia and Horn',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'SpSc 1011',
            'course_title' => 'Physical Fitness',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);

        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'EmTe1012',
            'course_title' => 'Introduction to Emerging Technologies',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Anth1012',
            'course_title' => 'Anthropology',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'MGMT 1012',
            'course_title' => 'Entrepreneurship',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Hist. 1012',
            'course_title' => 'History of Ethiopian and the Horn',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'EnLa1012',
            'course_title' => 'Communicative English II',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'MCiE1012',
            'course_title' => 'Moral and Ethical Education',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'SNIE1012',
            'course_title' => 'Inclusiveness',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);

        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn2031',
            'course_title' => 'Fundamemtals of Accounting I',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Mgmt2051',
            'course_title' => 'Interoduction to Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn2041',
            'course_title' => 'Mathematics for finance',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'ECON2072',
            'course_title' => 'Macroeconomics',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn2042',
            'course_title' => 'Fundamemtals of Information Systems',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Stata2011',
            'course_title' => 'Basic Statstics',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);

        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn2032',
            'course_title' => 'Fundamemtals of Accounting II',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn2043',
            'course_title' => 'Statistics for Fiance',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Mgmt2052',
            'course_title' => 'Principles of Marketing',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Mgmt2191',
            'course_title' => 'Operations Research',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Low2201',
            'course_title' => 'Business Law',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
       
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3081',
            'course_title' => 'Intermediate Finacial Accounting I',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3091',
            'course_title' => 'Cost and Management Accounting I',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3101',
            'course_title' => 'Financial Management I',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3091',
            'course_title' => 'Cost and Management Accounting I',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3121',
            'course_title' => 'Accounting for Public Sector & Civil Society',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'I',
        ]);

        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3082',
            'course_title' => 'Intermediate Finacial Accounting II',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3092',
            'course_title' => 'Cost and Management Accounting II',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3102',
            'course_title' => 'Financial Management II',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3113',
            'course_title' => 'Banking Principles and practices',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3171',
            'course_title' => 'Public Financial & Taxation',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn3131',
            'course_title' => 'Research Methods in Accounting & Finance',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);

        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4151',
            'course_title' => 'Advanced Financial Accounting',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4151',
            'course_title' => 'Advanced Financial Accounting',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4161',
            'course_title' => 'Auditing Principles and Practices I',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4181',
            'course_title' => 'Accounting Information Systems',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4241',
            'course_title' => 'Professional Practices in AcFn',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Mgmt3192',
            'course_title' => 'Operations Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4211',
            'course_title' => 'Senior Research Project I',
            'ects' => 0,
            'credit_hrs' => 1,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]); 
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4161',
            'course_title' => 'Econometrics for Finance',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);

        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4162',
            'course_title' => 'Auditing Principles and Practices II',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4212',
            'course_title' => 'Senior Research Project II',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4182',
            'course_title' => 'Accounting Software Application',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4202',
            'course_title' => 'Project Analysis & Evaluation',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'II',
        ]);
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'AcFn4201',
            'course_title' => 'Investement Analysis and portfolio Management',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'II',
        ]); 
        App\Accounting::create([
            'dept_name' => 'accounting',
            'course_code' => 'Mgmt4142',
            'course_title' => 'Strategic Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' =>0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'II',
        ]);
    }
}
