<?php

use Illuminate\Database\Seeder;

class ManagementTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'LoCT',
            'course_title' => 'Critical Thinking',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'Econ1011',
            'course_title' => 'Economics',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'IRGI1012',
            'course_title' => 'Global Trend',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'FLEn1011',
            'course_title' => 'Communicative English I',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'GeES1011',
            'course_title' => 'Geography of Ethiopia and the horn',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'Math1011',
            'course_title' => 'Mathematics for Social Sciences',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'Psyc1011',
            'course_title' => 'General Psychology',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'SpSc1011',
            'course_title' => 'Physical Fitness',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'I',
        ]);

        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'EmTe1012',
            'course_title' => 'Introduction to Emerging Technologies',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'Anth1012',
            'course_title' => 'Anthropology',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT1012',
            'course_title' => 'Enterpreneurship',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'Hist. 1012',
            'course_title' => 'History of Ethiopia and Horn',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'EnLa1012',
            'course_title' => 'Communicative Ednglish II',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MCiE1012',
            'course_title' => 'Moral and Ethical Education',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'SNIE1012',
            'course_title' => 'Inclusiveness',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 1,
            'semester' => 'II',
        ]);

        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'COMP2011',
            'course_title' => 'Basic Computer Skills',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'ENLA2011',
            'course_title' => 'Basic Writing Skills',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'ECON2161',
            'course_title' => 'Microeconomics',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 2061',
            'course_title' => 'Intoduction to Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 2062',
            'course_title' => 'Management Thought & Emerging Trends',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 2063',
            'course_title' => 'Administative & Business Commuunication',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'Stat2071',
            'course_title' => 'Intoduction to Statistics',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'I',
        ]);

        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 2131',
            'course_title' => 'Mathematics for Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 2093',
            'course_title' => 'Management Information System',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 2121',
            'course_title' => 'Principle of Marketing',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'ACFN2111',
            'course_title' => 'Principle of Accounting I',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 2072',
            'course_title' => 'Business Statistics',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'ECON2162',
            'course_title' => 'Macroeconomics',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 2,
            'semester' => 'II',
        ]);

        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT3081',
            'course_title' => 'Financial Institutions & Investment Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 3082',
            'course_title' => 'Organizational Behavior',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 2122',
            'course_title' => 'International Marketing',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'ACFN3112',
            'course_title' => 'Principles of Accounting II',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'I',
        ]);

        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'ECON3163',
            'course_title' => 'Interoduction to Econometrics',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT3091',
            'course_title' => 'Innovation & Technology Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT3012',
            'course_title' => 'Computerf Applications in Business',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 3083',
            'course_title' => 'Leadership and Change Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'II',
        ]);

        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 3162',
            'course_title' => 'Advanced Enterpreneurship and Enterprice Devlopment',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'III',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'ACFN3141',
            'course_title' => 'Cost and Management Accounting I',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'III',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 3211',
            'course_title' => 'Business Research Methods',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'III',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 3102',
            'course_title' => 'Business Ethics & Corporate Social Responsibility',
            'ects' => 0,
            'credit_hrs' => 2,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'III',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 3093',
            'course_title' => 'System Analysis and Design',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 3,
            'semester' => 'III',
        ]);

        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4081',
            'course_title' => 'Human Resource Management',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4101',
            'course_title' => 'Business Low',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'ACFN4142',
            'course_title' => 'Cost and Management Accounting II',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4132',
            'course_title' => 'Operations Resarch',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);

        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4151',
            'course_title' => 'Material Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4191',
            'course_title' => 'Operations Management',
            'ects' => 0,
            'credit_hrs' => 4,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'I',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4182',
            'course_title' => 'Financial Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'II',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4212',
            'course_title' => 'Research in Management I',
            'ects' => 0,
            'credit_hrs' => 1,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'II',
        ]);
        
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4192',
            'course_title' => 'Project Management',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'III',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4193',
            'course_title' => 'Risk Management and Insurance',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'III',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4201',
            'course_title' => 'Strategic Management and Policy Analysis',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'III',
        ]);
        App\Management::create([
            'dept_name' => 'management',
            'course_code' => 'MGMT 4213',
            'course_title' => 'Research in Management II',
            'ects' => 0,
            'credit_hrs' => 3,
            'lecture_hrs' => 0,
            'lab_hrs' => 0,
            'tutor_hrs' => 0,
            'year' => 4,
            'semester' => 'III',
        ]);
    }
}
